Attributes

In [1]:
import numpy as np

In [3]:
arr1 =np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [4]:
arr1.shape

(5,)

In [5]:
arr2 = np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
arr2.shape

(2, 3)

In [10]:
arr3 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
arr3

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [11]:
arr3.shape

(2, 2, 2)

In [12]:
arr2.ndim

2

In [13]:
arr1.ndim

1

In [14]:
arr1.size

5

In [15]:
arr2.size

6

In [16]:
arr3.size

8

In [19]:
arr3

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [20]:
arr3.itemsize

8

In [21]:
arr3.dtype

dtype('int64')

In [22]:
arr3.astype('float')

array([[[1., 2.],
        [3., 4.]],

       [[5., 6.],
        [7., 8.]]])