In [1]:
import numpy as np

In [3]:
# Scenario 1

a1 = np.arange(8).reshape(2,4)
a2 = np.arange(8,16).reshape(2,4)

print(a1)
print(a2)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [4]:
a1 + a2

array([[ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [7]:
# Scenario 2

a3 = np.arange(9).reshape(3,3)
a4 = np.arange(3).reshape(1,3)

print(a3,a4)

[[0 1 2]
 [3 4 5]
 [6 7 8]] [[0 1 2]]


In [8]:
a3 + a4

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10]])

Rules for Broadcasting

In [13]:
# If x=m and y=n, operation will take place

a1 = np.arange(8).reshape(2,4)
a2 = np.arange(8,16).reshape(2,4)

In [14]:
a1

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [15]:
a2

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [16]:
a1 + a2

array([[ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [24]:
# If x=1 and y=n then operation will take place (Same Dimension)

a5 = np.arange(3).reshape(1,3)
a6 = np.arange(12).reshape(4,3)

print(a5)
print(a6)

[[0 1 2]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [25]:
a5 + a6

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10],
       [ 9, 11, 13]])

In [30]:
# If y=1 and x=m then also operation will take place, even if
# they are not of same dimension

a7 = np.arange(4).reshape(4,1)
a8 = np.arange(12).reshape(4,3)

print(a7)
print(a8)

[[0]
 [1]
 [2]
 [3]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [31]:
a7 + a8

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14]])

In [32]:
# If x=1 and y!=n then also operation will not take place

a9 = np.arange(3).reshape(1,3)
a10 = np.arange(16).reshape(4,4)

print(a9)
print(a10)

[[0 1 2]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [34]:
# If x=1 and n=1 then y==m,operation to takes place

a11 = np.arange(3).reshape(1,3)
a12 = np.arange(3).reshape(3,1)

print(a11)
print(a12)

[[0 1 2]]
[[0]
 [1]
 [2]]


In [35]:
a11 + a12

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [37]:
# If x=1 and y=1, then the operation will take place no matter what

a13 = np.arange(1).reshape(1,1)
a14 = np.arange(20).reshape(4,5)

print(a13)
print(a14)

[[0]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [38]:
a13 + a14

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [39]:
# If they are of different dimension

a15 = np.arange(4)
a16 = np.arange(20).reshape(5,4)

print(a15)
print(a16)

[0 1 2 3]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [40]:
a15 + a16

array([[ 0,  2,  4,  6],
       [ 4,  6,  8, 10],
       [ 8, 10, 12, 14],
       [12, 14, 16, 18],
       [16, 18, 20, 22]])