In [1]:
#creating numpy/n-d arrays
import numpy as np

In [2]:
arr1 = np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [3]:
type(arr1)

numpy.ndarray

In [6]:
arr2 = np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
arr3 = np.zeros((2,3))
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [8]:
arr4 = np.ones((3,3))
arr4

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [9]:
arr5 = np.identity(5)

In [10]:
arr5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [13]:
arr6 = np.arange(5,16)
arr6

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [14]:
arr6 = np.arange(5,16,2)
arr6

array([ 5,  7,  9, 11, 13, 15])

In [15]:
arr7 = np.linspace(10,20,10)
arr7

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [16]:
arr8 = arr7.copy()
arr8

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])