In [1]:
import numpy as np

In [2]:
arr = np.random.randint(low=1,high=100,size=20).reshape(4,5)

In [3]:
arr

array([[24, 70, 59, 72, 61],
       [ 3, 57, 11, 51, 52],
       [52, 92, 19, 56, 30],
       [58,  2, 93, 29, 85]])

In [4]:
#Indexing using Boolean Arrays
arr[arr>50]

array([70, 59, 72, 61, 57, 51, 52, 52, 92, 56, 58, 93, 85])

In [5]:
arr[(arr>50) & (arr%2!=0)]

array([59, 61, 57, 51, 93, 85])

In [6]:
arr[(arr>50) & (arr%2!=0)] = 0

In [7]:
arr

array([[24, 70,  0, 72,  0],
       [ 3,  0, 11,  0, 52],
       [52, 92, 19, 56, 30],
       [58,  2,  0, 29,  0]])