In [1]:
import numpy as np

In [2]:
np.random.random()

0.4505920481346609

In [3]:
np.random.seed(1)
np.random.random()

0.417022004702574

In [10]:
np.random.uniform(1,100)

42.68965487550017

In [12]:
np.random.uniform(1,100,10).reshape(2,5)

array([[28.76395521, 79.13865352, 11.21937465, 45.34145909, 90.95095481],
       [30.06780069, 29.48975852, 13.87282864,  2.91732883, 68.20471776]])

In [14]:
np.random.randint(1,10)

1

In [15]:
np.random.randint(1,10,15).reshape(3,5)

array([[3, 8, 8, 8, 4],
       [1, 9, 8, 8, 2],
       [2, 4, 1, 9, 7]])

In [16]:
a = np.random.randint(1,10,6)

In [17]:
a

array([5, 6, 7, 3, 6, 8])

In [19]:
np.max(a)

np.int64(8)

In [20]:
np.min(a)

np.int64(3)

In [21]:
np.argmax(a)

np.int64(5)

In [22]:
a[np.argmax(a)]

np.int64(8)

In [23]:
np.argmin(a)

np.int64(3)

In [24]:
a[np.argmin(a)]

np.int64(3)

In [25]:
a = np.random.randint(1,10,6)
a

array([9, 5, 5, 8, 8, 5])

In [27]:
a[a%2==1] = -1
a

array([-1, -1, -1,  8,  8, -1])

In [28]:
a = np.random.randint(1,50,6)
a

array([49, 19, 33, 14, 11, 24])

In [30]:
np.where(a%2==1,-1,a)

array([-1, -1, -1, 14, -1, 24])

In [31]:
a

array([49, 19, 33, 14, 11, 24])

In [32]:
out = np.where(a%2==1,-1,a)
out

array([-1, -1, -1, 14, -1, 24])

In [33]:
a = np.random.randint(1,50,10)
a

array([18,  8, 25, 11, 29, 21, 33, 13,  2, 31])

In [34]:
a = np.sort(a)
a

array([ 2,  8, 11, 13, 18, 21, 25, 29, 31, 33])

In [35]:
np.percentile(a,25)

np.float64(11.5)

In [36]:
np.percentile(a,50)

np.float64(19.5)

In [37]:
np.percentile(a,99.8)

np.float64(32.964)