In [2]:
import numpy as np

In [3]:
arr3 = np.arange(6).reshape(2,3)

In [4]:
arr3

array([[0, 1, 2],
       [3, 4, 5]])

In [5]:
arr4 = np.arange(6,12).reshape(3,2)

In [6]:
arr4

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [7]:
arr4.ndim

2

In [8]:
arr4.ravel()

array([ 6,  7,  8,  9, 10, 11])

In [9]:
arr4.transpose()

array([[ 6,  8, 10],
       [ 7,  9, 11]])

In [11]:
arr5 = np.arange(12,18).reshape(2,3)

In [12]:
arr5

array([[12, 13, 14],
       [15, 16, 17]])

In [14]:
np.hstack((arr3,arr5))

array([[ 0,  1,  2, 12, 13, 14],
       [ 3,  4,  5, 15, 16, 17]])

In [16]:
np.vstack((arr3,arr5))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [12, 13, 14],
       [15, 16, 17]])

In [17]:
np.hsplit(arr3,3)

[array([[0],
        [3]]),
 array([[1],
        [4]]),
 array([[2],
        [5]])]

In [18]:
 np.vsplit(arr3,2)

[array([[0, 1, 2]]), array([[3, 4, 5]])]